"""
Author: Roa'a Khaled
Affiliation: Department of Computer Engineering, Department of Condensed Matter Physics,
             University of Cádiz, , Puerto Real, 11519, Cádiz, Spain.
Email: roaa.khaled@gm.uca.es
Date: 2025-07-27
Project: This work is part of a predoctoral research and part of PARENT project that has received funding
         from the EU’s Horizon 2020 research and innovation program under the MSCA – ITN 2020, GA No 956394.

Description:
    This code sets up all needed directories and parameters for running inference using the script
    (local_cpu_inference.py) which uses a previously trained 2D UNet model to segment testing/inference data, the model
    was trained for Total Brains segmentation from cranial Ultrasound images of premature born infants.

Usage:
    import local_inference_config

Notes:
    - for environment requirements check
"""

# import the necessary packages
import torch
import os

##Inference on Testing/Inference Set##
# path of the trained model
MODEL_PATH = "path\of\model\weights" # path of .pth file, ex.: "\Total-Brain-Segmentation-from-cUS\2D UNet\Trained Models\Axial\Axial_2DUNet_model.pth"
# path to the .txt file with all the testing images paths of all patients --> if you train your own using our training script, it will be generated by the script train_2dUNet.py
TESTING_IMAGES_PATHS = "path\of\testing\slices2D\paths"
# path of the inference outputs (segmentations)
PREDICTIONS_PATH = "path\of\output\predictions"
# define the input image dimensions
# input image size
INPUT_IMAGE_WIDTH = 256
INPUT_IMAGE_HEIGHT = 256

